#!/usr/bin/env python3
"""
master_pipeline.py
──────────────────
THE MASTER PIPELINE — ONE COMMAND, FULL QUARTER

Reads a quarterly config YAML and:
  1. Generates Mapflow download configs per dataset
  2. Runs Mapflow to download from TomTom API
  3. Runs ingest.sh to organise folder structure
  4. Auto-generates client_distribution.csv
  5. Runs provision_clients.py to update Nextcloud users/groups/mounts
  6. Triggers Nextcloud file scan
  7. Sends email notifications to clients (optional)

Usage:
  python3 master_pipeline.py --quarter Q2_2026 --dry-run
  python3 master_pipeline.py --quarter Q2_2026
  python3 master_pipeline.py --quarter Q2_2026 --skip-download
  python3 master_pipeline.py --quarter Q2_2026 --only-clients Esri,Altrack

Requirements:
  pip install pyyaml pandas python-dotenv
"""

import argparse
import csv
import os
import subprocess
import sys
import uuid
from datetime import datetime
from pathlib import Path

import yaml
from dotenv import load_dotenv

# ── Colours ───────────────────────────────────────────────────
GREEN  = "\033[0;32m"; YELLOW = "\033[1;33m"
RED    = "\033[0;31m"; CYAN   = "\033[0;36m"
BOLD   = "\033[1m";    NC     = "\033[0m"

def ts():     return datetime.now().strftime("%Y-%m-%d %H:%M:%S")
def info(m):  print(f"[{ts()}]{CYAN}[INFO]{NC}  {m}", flush=True)
def ok(m):    print(f"[{ts()}]{GREEN}[OK]{NC}    {m}", flush=True)
def warn(m):  print(f"[{ts()}]{YELLOW}[WARN]{NC}  {m}", flush=True)
def error(m): print(f"[{ts()}]{RED}[ERROR]{NC} {m}"); sys.exit(1)
def section(m): print(f"\n{BOLD}{CYAN}━━━  {m}  ━━━{NC}\n", flush=True)

SCRIPT_DIR = Path(__file__).parent
NC_PATH    = "/var/www/html/nextcloud"

# ── Dataset → folder mapping (mirrors ingest.sh logic) ────────
DATASET_DEST_MAP = {
    "MNR": lambda region, distro: f"{distro}/MNR/MNR_{region}",
    "MN":  lambda region, distro: f"{distro}/MN/MN_{region}",
    "SP":  lambda region, distro: f"{distro}/PRODUCTS/SPEED_PROFILES/SPEED_PROFILES_{region}",
    "POI": lambda region, distro: f"{distro}/PRODUCTS/MN_PREMIUM_POI/MN_PREMIUM_POI_{region}",
    "APT": lambda region, distro: f"{distro}/PRODUCTS/MN_APT/MN_APT_{region}",
}

# ── Family → short prefix (for .folders.env keys) ─────────────
FAMILY_PREFIX = {
    "MNR": "MNR", "MULTINET_R": "MNR",
    "MN":  "MN",  "MULTINET":   "MN",
    "MNSP": "SP", "Speed Profiles": "SP",
    "MNPOI": "POI",
    "MNAP":  "APT",
}


def load_quarterly_config(quarter: str) -> dict:
    """Load the quarterly YAML config file."""
    config_path = SCRIPT_DIR / "quarterly" / f"{quarter}.yaml"
    if not config_path.exists():
        error(f"Quarterly config not found: {config_path}")
    with open(config_path) as f:
        return yaml.safe_load(f)


def generate_mapflow_config(dataset_key: str, dataset: dict,
                             quarterly: dict, output_dir: Path) -> Path:
    """Generate a Mapflow YAML config for one dataset."""
    family   = dataset["family"]
    region   = dataset["region"]
    zones    = dataset.get("zones", "~ALL")
    mnr_data = dataset.get("mnr_data", [])
    version  = quarterly["tomtom_version"]

    # Build zones list
    if zones == "~ALL":
        zones_yaml = f"[~ALL, ]"
    else:
        zones_str = ", ".join(f"'{z}'" for z in zones)
        zones_yaml = f"[{zones_str}]"

    # Build mnr_data line
    if mnr_data and mnr_data != ["ALL"]:
        mnr_line = f"  mnr_data: [{', '.join(mnr_data)}]"
    elif mnr_data == ["ALL"]:
        mnr_line = "  mnr_data: [ALL]"
    else:
        mnr_line = ""

    config_id = str(uuid.uuid4())
    quarter   = quarterly["quarter"]
    downloads = quarterly["downloads_folder"]

    config_content = f"""# Auto-generated by master_pipeline.py
# Quarter: {quarter} | Dataset: {dataset_key}
# Generated: {datetime.now().isoformat()}
id: {config_id}
client: GEOINT
group: {dataset_key}
tomtom:
  family: {family}
  regions:
  - {region}: {zones_yaml}
  version: {version}
  iteration: COMMERCIAL
  delivery: FULL
{mnr_line}
operations:
- obtain:
    destination:
      server:
        host: ${{MAPFLOW_SERVER_HOST}}
        port: ${{MAPFLOW_SERVER_PORT}}
      datatype: MNR
      local_directory: "{downloads}"
    tasks:
    - tt_api
    - tt_download
    - tt_uncompress
    - alert
"""

    output_path = output_dir / f"auto_{dataset_key.lower()}_{quarter.lower()}.yaml"
    output_path.write_text(config_content)
    return output_path


def run_mapflow(config_path: Path, mapflow_dir: Path, dry_run: bool) -> bool:
    """Run Mapflow for a single dataset config."""
    if dry_run:
        info(f"  [DRY-RUN] Would run Mapflow with: {config_path.name}")
        return True

    env = os.environ.copy()
    env["CONFIG"] = str(config_path)
    env["LOG_LEVEL"] = "INFO"

    cmd = ["python", "-m", "mapflow.main"]
    info(f"  Running Mapflow: {config_path.name}")
    result = subprocess.run(
        cmd,
        cwd=str(mapflow_dir / "code"),
        env=env,
        capture_output=False
    )
    if result.returncode != 0:
        warn(f"  Mapflow exited with code {result.returncode} for {config_path.name}")
        return False
    ok(f"  Mapflow complete: {config_path.name}")
    return True


def generate_folders_env(quarterly: dict, datasets: list, output_path: Path):
    """Generate .folders.env for ingest.sh from quarterly config."""
    quarter      = quarterly["quarter"]
    distro       = quarterly["distro_folder"]
    downloads    = quarterly["downloads_folder"]
    version      = quarterly["tomtom_version"]
    # version like 2026.06.003 → q2_202606003
    ver_clean    = version.replace(".", "").replace("-", "")

    lines = [
        f"# Auto-generated by master_pipeline.py — {datetime.now().isoformat()}",
        f"# Quarter: {quarter}",
        f"DISTRO_FOLDER={distro}",
        f"DATA_FOLDER={downloads}",
        "",
    ]

    for key in datasets:
        dataset = quarterly["datasets"][key]
        family  = dataset["family"]
        region  = dataset["region"]
        prefix  = FAMILY_PREFIX.get(family, family)
        env_key = f"{prefix}_{region}"

        # Build the expected download folder name
        # Mapflow creates: {downloads}/{family}_{region}_{version}_commercial_full/data/{region_lower}
        family_name_map = {
            "MNR": "MultiNet-R", "MULTINET_R": "MultiNet-R",
            "MN":  "MultiNet",
            "MNSP": "MultiNet-SpeedProfile",
            "MNPOI": "MultiNet-POI",
            "MNAP": "MultiNet-AddressPoints",
        }
        fname = family_name_map.get(family, family)
        folder = f"{fname}_{region}_{version}_commercial_full/data/{region.lower()}"
        lines.append(f"{env_key}={folder}")

    output_path.write_text("\n".join(lines) + "\n")
    ok(f"Generated .folders.env: {output_path}")


def generate_csv(quarterly: dict, output_path: Path):
    """
    Auto-generate client_distribution.csv from the quarterly config.
    Maps clients → datasets → actual folder paths on disk.
    """
    distro   = quarterly["distro_folder"]
    quarter  = quarterly["quarter"]
    clients  = quarterly["clients"]
    datasets = quarterly["datasets"]

    rows = []
    for client_name, client_cfg in clients.items():
        username    = client_cfg["username"]
        client_datasets = client_cfg["datasets"]
        # Generate a UUID password (or keep existing one — loaded from prev CSV)
        password = str(uuid.uuid4())
        first_row = True

        for dataset_key in client_datasets:
            if dataset_key not in datasets:
                warn(f"Dataset {dataset_key} not in quarterly config — skipping")
                continue

            dataset = datasets[dataset_key]
            family  = dataset["family"]
            region  = dataset["region"]
            prefix  = FAMILY_PREFIX.get(family, family)
            dest    = DATASET_DEST_MAP.get(prefix, lambda r, d: d)(region, distro)

            rows.append({
                "CLIENT":        client_name if first_row else "",
                "PASSWORD":      password    if first_row else "",
                "DATA":          dataset_key,
                "GROUP":         f"{prefix.lower()}_{region.lower()}",
                "DirectoryPath": dest,
            })
            first_row = False

    with open(output_path, "w", newline="") as f:
        writer = csv.DictWriter(
            f, fieldnames=["CLIENT", "PASSWORD", "DATA", "GROUP", "DirectoryPath"])
        writer.writeheader()
        writer.writerows(rows)

    ok(f"Generated CSV: {output_path} ({len(rows)} rows, {len(clients)} clients)")
    return output_path


def run_ingest(folders_env: Path, distro_folder: str,
               log_file: Path, dry_run: bool) -> bool:
    """Run ingest.sh to organise downloaded files."""
    ingest_script = SCRIPT_DIR / "scripts" / "ingest.sh"
    if not ingest_script.exists():
        warn(f"ingest.sh not found at {ingest_script} — skipping ingest step")
        return False

    cmd = ["bash", str(ingest_script), "--env", str(folders_env), "--log", str(log_file)]
    if dry_run:
        cmd.append("--dry-run")

    info(f"  Running ingest.sh...")
    result = subprocess.run(cmd, capture_output=False)
    if result.returncode != 0:
        warn(f"  ingest.sh exited with code {result.returncode}")
        return False
    ok("  ingest.sh complete")
    return True


def run_provision(csv_path: Path, env_path: Path, dry_run: bool) -> bool:
    """Run provision_clients.py to update Nextcloud."""
    provision_script = SCRIPT_DIR / "scripts" / "provision_clients.py"
    if not provision_script.exists():
        warn(f"provision_clients.py not found — skipping provision step")
        return False

    cmd = [sys.executable, str(provision_script),
           "--env", str(env_path),
           "--csv", str(csv_path),
           "--report"]
    if dry_run:
        cmd.append("--dry-run")

    info("  Running provision_clients.py...")
    result = subprocess.run(cmd, capture_output=False)
    if result.returncode != 0:
        warn(f"  provision_clients.py exited with code {result.returncode}")
        return False
    ok("  Nextcloud provisioning complete")
    return True


def trigger_nextcloud_scan(dry_run: bool):
    """Trigger Nextcloud file scan."""
    if dry_run:
        info("  [DRY-RUN] Would trigger: occ files:scan --all")
        return
    occ = Path(NC_PATH) / "occ"
    if occ.exists():
        subprocess.run(
            ["sudo", "-u", "www-data", "php", str(occ), "files:scan", "--all"],
            capture_output=True)
        ok("  Nextcloud file scan triggered")
    else:
        warn(f"  Nextcloud occ not found at {NC_PATH}")


def main():
    parser = argparse.ArgumentParser(
        description="Master quarterly data distribution pipeline")
    parser.add_argument("--quarter",        required=True, help="e.g. Q2_2026")
    parser.add_argument("--env",            default="config/.env")
    parser.add_argument("--mapflow-dir",    default="/opt/mapflow",
                        help="Path to Mapflow project root")
    parser.add_argument("--dry-run",        action="store_true")
    parser.add_argument("--skip-download",  action="store_true",
                        help="Skip Mapflow download step")
    parser.add_argument("--skip-ingest",    action="store_true",
                        help="Skip ingest.sh step")
    parser.add_argument("--skip-provision", action="store_true",
                        help="Skip Nextcloud provisioning step")
    parser.add_argument("--only-datasets",  help="Comma-separated dataset keys to download")
    parser.add_argument("--only-clients",   help="Comma-separated client names")
    args = parser.parse_args()

    load_dotenv(args.env)

    print(f"\n{BOLD}{CYAN}╔══════════════════════════════════════════════════╗")
    print(f"║  MASTER PIPELINE — {args.quarter:<30} ║")
    print(f"║  {datetime.now().strftime('%Y-%m-%d %H:%M:%S'):<48} ║")
    print(f"╚══════════════════════════════════════════════════╝{NC}\n")

    if args.dry_run:
        warn("DRY-RUN MODE — no files will be changed\n")

    # ── Load quarterly config ──────────────────────────────────
    section("Loading Configuration")
    quarterly = load_quarterly_config(args.quarter)
    quarter     = quarterly["quarter"]
    distro      = quarterly["distro_folder"]
    info(f"Quarter:      {quarter}")
    info(f"TomTom ver:   {quarterly['tomtom_version']}")
    info(f"Distro:       {distro}")
    info(f"Clients:      {len(quarterly['clients'])}")
    info(f"Datasets:     {len(quarterly['datasets'])}")

    # Filter datasets/clients if requested
    active_datasets = list(quarterly["datasets"].keys())
    if args.only_datasets:
        active_datasets = [d.strip() for d in args.only_datasets.split(",")]
        info(f"Filtered to datasets: {active_datasets}")

    active_clients = quarterly["clients"]
    if args.only_clients:
        filter_names = [c.strip() for c in args.only_clients.split(",")]
        active_clients = {k: v for k, v in quarterly["clients"].items()
                         if k in filter_names}
        info(f"Filtered to clients: {list(active_clients.keys())}")

    # ── Create working dirs ────────────────────────────────────
    work_dir = SCRIPT_DIR / "quarterly" / quarter
    work_dir.mkdir(parents=True, exist_ok=True)
    log_dir  = SCRIPT_DIR / "logs"
    log_dir.mkdir(exist_ok=True)

    # ── Step 1: Generate Mapflow configs ──────────────────────
    if not args.skip_download:
        section("Step 1 — Generating Mapflow Download Configs")
        mapflow_configs = {}
        for key in active_datasets:
            dataset = quarterly["datasets"][key]
            cfg_path = generate_mapflow_config(
                key, dataset, quarterly, work_dir)
            mapflow_configs[key] = cfg_path
            ok(f"  Config: {cfg_path.name}")

        # ── Step 2: Run Mapflow downloads ──────────────────────
        section("Step 2 — Downloading from TomTom API via Mapflow")
        mapflow_dir = Path(args.mapflow_dir)
        if not mapflow_dir.exists():
            warn(f"Mapflow not found at {mapflow_dir} — skipping downloads")
            warn("Set --mapflow-dir to your Mapflow project root")
        else:
            for key, cfg_path in mapflow_configs.items():
                info(f"Downloading: {key}")
                run_mapflow(cfg_path, mapflow_dir, args.dry_run)
    else:
        info("Skipping download step (--skip-download)")

    # ── Step 3: Generate .folders.env ─────────────────────────
    section("Step 3 — Generating .folders.env for ingest.sh")
    folders_env = work_dir / ".folders.env"
    generate_folders_env(quarterly, active_datasets, folders_env)

    # ── Step 4: Run ingest.sh ──────────────────────────────────
    if not args.skip_ingest:
        section("Step 4 — Running ingest.sh")
        log_file = log_dir / f"ingest_{quarter}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"
        run_ingest(folders_env, distro, log_file, args.dry_run)
    else:
        info("Skipping ingest step (--skip-ingest)")

    # ── Step 5: Generate CSV ───────────────────────────────────
    section("Step 5 — Generating client_distribution.csv")
    # Use filtered clients
    quarterly_filtered = dict(quarterly)
    quarterly_filtered["clients"] = active_clients
    csv_path = SCRIPT_DIR / "data" / f"client_distribution_{quarter}.csv"
    csv_path.parent.mkdir(exist_ok=True)
    generate_csv(quarterly_filtered, csv_path)
    # Also update the main CSV
    main_csv = SCRIPT_DIR / "data" / "client_distribution.csv"
    import shutil
    if not args.dry_run:
        # Archive previous
        prev_csv = SCRIPT_DIR / "data" / "prev_quarter.csv"
        if main_csv.exists():
            shutil.copy(main_csv, prev_csv)
            info(f"Archived previous CSV to: {prev_csv.name}")
        shutil.copy(csv_path, main_csv)
        ok(f"Updated main CSV: {main_csv}")

    # ── Step 6: Provision Nextcloud ────────────────────────────
    if not args.skip_provision:
        section("Step 6 — Provisioning Nextcloud")
        run_provision(csv_path, Path(args.env), args.dry_run)
        trigger_nextcloud_scan(args.dry_run)
    else:
        info("Skipping provision step (--skip-provision)")

    # ── Done ───────────────────────────────────────────────────
    print(f"\n{BOLD}{GREEN}╔══════════════════════════════════════════════════╗")
    print(f"║  PIPELINE COMPLETE — {quarter:<28} ║")
    print(f"║                                                  ║")
    print(f"║  Next steps:                                     ║")
    print(f"║  1. Verify data in {distro[:28]:<28} ║")
    print(f"║  2. Test client logins in Nextcloud              ║")
    print(f"║  3. Send notifications to clients                ║")
    print(f"║     python3 agents/agent_notify.py \\             ║")
    print(f"║       --quarter {quarter:<34} ║")
    print(f"╚══════════════════════════════════════════════════╝{NC}\n")


if __name__ == "__main__":
    main()
