#!/usr/bin/env bash
# =============================================================
#  download_mapit.sh — MAPIT DATA DOWNLOADER
#  ─────────────────────────────────────────────────────────────
#  Downloads MAPIT data from the provider's SFTP server.
#  Runs independently from the TomTom download pipeline.
#
#  Usage:
#    cd /mnt/data/MapFlow/mapflow
#    source .venv/bin/activate
#    bash download_mapit.sh
#
#  After download completes, files land in:
#    /mnt/data/downloads/mapit/
#  Then copy manually to:
#    /mnt/data/DISTRIBUTION_QX_XXXX/MAPIT/SQL/MAPIT_SQL_ZAF
#    /mnt/data/DISTRIBUTION_QX_XXXX/MAPIT/SQL/MAPIT_SQL_AFR
# =============================================================

set -Eeuo pipefail

# ── Environment ───────────────────────────────────────────────
set -o allexport; source /mnt/data/MapFlow/mapflow/.env; set +o allexport
export LOG_LEVEL=INFO

# ── Directories ───────────────────────────────────────────────
DOWNLOAD_DIR='/mnt/data/downloads/mapit'
MAPFLOW_DIR='/mnt/data/MapFlow/mapflow'
CONFIG_FILE="$MAPFLOW_DIR/configs/auto_mapit.yaml"
mkdir -p "$DOWNLOAD_DIR"

# =============================================================
#  EDIT THIS SECTION EACH QUARTER
# =============================================================

QUARTER="Q2_2026"
MAPIT_VERSION="202606"        # ← Format: YYYYMM — update each quarter

# Which MAPIT areas to download:
# Options: SOUTH, ZAF, CENTRAL, EAST, WEST, ISLANDS
# ZAF     → Knowledge_Factory, Lightstone
# SOUTH   → Southern Africa clients
# CENTRAL → Esri (Africa)
AREAS="[SOUTH, ZAF]"

# Provider SFTP settings — set in .env file:
# MAPIT_SFTP_HOST=sftp.yourprovider.com
# MAPIT_SFTP_PORT=22
# MAPIT_SFTP_USER=yourusername
# MAPIT_SFTP_PASS=yourpassword
# MAPIT_SFTP_DIR=your/remote/directory
# MAPIT_SFTP_DATA_DIR=version_specific_subdir

# =============================================================
#  DO NOT EDIT BELOW THIS LINE
# =============================================================

CONFIG_ID=$(python3 -c "import uuid; print(uuid.uuid4())")

cat > "$CONFIG_FILE" << EOF
# Auto-generated by download_mapit.sh — $(date '+%Y-%m-%d %H:%M:%S')
# Quarter: ${QUARTER} | Version: ${MAPIT_VERSION}
id: ${CONFIG_ID}
client: GEOINT
group: ${QUARTER}_MAPIT
tomtom:
  family: MAPIT
  areas: ${AREAS}
  version: '${MAPIT_VERSION}'
operations:
- obtain:
    destination:
      server:
        host: \${MAPIT_SFTP_HOST}
        port: \${MAPIT_SFTP_PORT}
      datatype: MSSQL
      local_directory: "${DOWNLOAD_DIR}"
    tasks:
    - mi_download
    - mi_uncompress
    - alert
EOF

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  MAPIT Download Starting"
echo "  Quarter:  $QUARTER"
echo "  Version:  $MAPIT_VERSION"
echo "  Areas:    $AREAS"
echo "  Dest:     $DOWNLOAD_DIR"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

export CONFIG="$CONFIG_FILE"
export DATA_DIR="$DOWNLOAD_DIR"

# SFTP settings from .env
export RISKSCAPE_URL="${MAPIT_SFTP_HOST:-}"
export RISKSCAPE_PORT="${MAPIT_SFTP_PORT:-22}"
export RISKSCAPE_USER="${MAPIT_SFTP_USER:-}"
export RISKSCAPE_PASS="${MAPIT_SFTP_PASS:-}"
export RISKSCAPE_DIR="${MAPIT_SFTP_DIR:-}"
export RISKSCAPE_DATA_DIR="${MAPIT_SFTP_DATA_DIR:-}"

cd "$MAPFLOW_DIR/code"
python -m mapflow.main

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  MAPIT download complete!"
echo "  Files in: $DOWNLOAD_DIR"
echo ""
echo "  Next — copy to distribution folder:"
echo "  cp -r $DOWNLOAD_DIR/ZAF/* \\"
echo "    /mnt/data/DISTRIBUTION_${QUARTER}/MAPIT/SQL/MAPIT_SQL_ZAF/"
echo "  cp -r $DOWNLOAD_DIR/SOUTH/* \\"
echo "    /mnt/data/DISTRIBUTION_${QUARTER}/MAPIT/SQL/MAPIT_SQL_AFR/"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
