#!/usr/bin/env bash
# =============================================================
#  download.sh — TOMTOM DATA DOWNLOADER
#  ─────────────────────────────────────────────────────────────
#  Downloads TomTom data via the Mapflow API client.
#  Edit the REGIONS and DATASET sections each quarter.
#
#  Usage:
#    cd /mnt/data/MapFlow/mapflow
#    source .venv/bin/activate
#    bash download.sh
#
#  After download completes, run ingest.sh to organise files.
# =============================================================

set -Eeuo pipefail

# ── Environment ───────────────────────────────────────────────
set -o allexport; source /mnt/data/MapFlow/mapflow/.env; set +o allexport
export LOG_LEVEL=INFO

# ── Directories ───────────────────────────────────────────────
DOWNLOAD_DIR='/mnt/data/downloads'
MAPFLOW_DIR='/mnt/data/MapFlow/mapflow'
CONFIG_FILE="$MAPFLOW_DIR/configs/auto_download.yaml"
mkdir -p "$DOWNLOAD_DIR"
mkdir -p "$(dirname "$CONFIG_FILE")"

# =============================================================
#  EDIT THIS SECTION EACH QUARTER
# =============================================================

QUARTER="Q2_2026"
TOMTOM_VERSION="2026.06.003"   # ← update each quarter

# Choose ONE family per run. Run this script once per product type.
# Options: MNR, MN, MNSP (Speed Profiles), MNPOI (POI), MNAP (APT)
FAMILY="MNR"

# Layers to download (MNR only). Options:
#   [ALL] — everything
#   [core, apt, speed_profiles, buildings, poi, ada, geospatial,
#    geopolitical, logistics, generic, level_0, phonemes]
MNR_LAYERS="[core, apt, speed_profiles]"

# ── Regions & countries ───────────────────────────────────────
# Uncomment the regions you need. Use ~ALL for every country in a region.
# Comment out regions not needed this quarter.
REGIONS=$(cat <<'YAML'
  regions:
  - MEA: [~ALL]
#  - EUR: [~ALL]
#  - MEA: [ZAF, LSO, NAM, BWA, SWZ, MOZ, MWI, ZMB, ZWE, AGO]
#  - MEA: [SAU, OMN, KWT, QAT, ARE, BHR, IRQ, JOR, LBN, YEM]
YAML
)

# =============================================================
#  DO NOT EDIT BELOW THIS LINE
# =============================================================

# Generate a valid UUID for the config ID
CONFIG_ID=$(python3 -c "import uuid; print(uuid.uuid4())")

# Build mnr_data line only for MNR family
if [[ "$FAMILY" == "MNR" ]]; then
    MNR_DATA_LINE="  mnr_data: ${MNR_LAYERS}"
else
    MNR_DATA_LINE=""
fi

# Write the config file
cat > "$CONFIG_FILE" << EOF
# Auto-generated by download.sh — $(date '+%Y-%m-%d %H:%M:%S')
# Quarter: ${QUARTER} | Family: ${FAMILY} | Version: ${TOMTOM_VERSION}
id: ${CONFIG_ID}
client: GEOINT
group: ${QUARTER}
tomtom:
  family: ${FAMILY}
${REGIONS}
  version: '${TOMTOM_VERSION}'
  iteration: COMMERCIAL
  delivery: FULL
${MNR_DATA_LINE}
operations:
- obtain:
    destination:
      server:
        host: localhost
        port: 1234
      datatype: MNR
      local_directory: "${DOWNLOAD_DIR}"
    tasks:
    - tt_api
    - tt_download
    - tt_uncompress
    - alert
EOF

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  TomTom Download Starting"
echo "  Quarter:  $QUARTER"
echo "  Family:   $FAMILY"
echo "  Version:  $TOMTOM_VERSION"
echo "  Dest:     $DOWNLOAD_DIR"
echo "  Config:   $CONFIG_FILE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

export CONFIG="$CONFIG_FILE"
export DATA_DIR="$DOWNLOAD_DIR"

cd "$MAPFLOW_DIR/code"
python -m mapflow.main

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Download complete!"
echo "  Files in: $DOWNLOAD_DIR"
echo ""
echo "  Next step — run ingest.sh:"
echo "  cd /opt/nextcloud-setup/nextcloud-data-distribution"
echo "  sudo bash scripts/ingest.sh --env .folders.env"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
